### ISSUE TITLE
Videos with ?autoplay start playing again after popup closed.

### ISSUE THREAD

**Issue by danieliser** [danieliser/Popup-Maker#1]
When removing and re-adding the src of the video IFrame, it needs to strip ?autoplay from the URL to prevent playing again.

**Comment by danieliser** [comment]
Still not working for the following video iframe

<iframe width="1280" height="300" src="//www.youtube.com/embed/G3u_F1Wn7H8?rel=0&autoplay=1" frameborder="0" allowfullscreen></iframe>

**Comment by danieliser** [comment]
Unable to duplicate. Awaiting further user input. Bumping from v1.1.8

**Comment by danieliser** [comment]
OP said the issue seems to have been resolved after all.

**Comment by dandyxu** [comment]
Hi, there

I added "?autoplay=1" in the end of youtube link. However, the popup does not appear again but because the video has the voice, it's actually playing the video automatically in the background even the popup doesn't appear.

I suppose it might be a bug. Can you double check this issue again please?

Thank you very much.

**Comment by danieliser** [comment]
@dandyxu Couple things to check:

- JS errors in your console
- Search the html to be sure your custom code is there
- Make sure the ?autoplay is not in the link when you edit your popup, it should only be added when the popup actually is opened.
- Make sure the #pum-123 part matches your videos actual popup ID #. IE 123 is a placeholder

That said you may opt to wait a few days for the release of our awesome new extension ;)

You can see it in action via https://wppopupmaker.com/extensions/age-verification-modals/ in the videos section. Completely customizable player with CSS, plenty of options to do the above in a few clicks, loads the videos on demand (insanely faster than the standard embedded iframe), even extra JS events for you to hook into such as when they get to a certain point in the video :+1:

**Comment by dandyxu** [comment]
@danieliser Hi, Daniel

Thanks for your reply and routes for checking.

I followed your suggestions:
1) No JS errors in my browser console;
2) In the Inspect, I can make sure my custom code is there;
Basically I copy and paste your code snippets into my footer.php and place them into <script></script>
3) I don't add ?autoplay=1 in the <iframe> link in the editor;
4) I found the actual popup ID and replace with placeholder.

Unfortunately, the autoplay still doesn't work. Do you have other ideas for checking this issue?

Thank you very much and hope to hear from you soon.

**Comment by danieliser** [comment]
@dandyxu - Got a link?

**Comment by puregraphx** [comment]
Same issue here. Popup is hidden (display:none) correctly after first play thanks to cookie, but the YouTube autoplay movie keeps looping and looping. Maybe you can remove the popup from the HTML flow when cookie is set, instead of just use display:none?

**Comment by danieliser** [comment]
@puregraphx This isn't a bug and won't be changed. We have solutions in our [docs](http://docs.wppopupmaker.com/article/86-start-video-when-the-popup-opens) for your needs, but it boils down to this.

1. We have a premium extension that offers delayed loading, play on open, etc.
1. There are many situations when you wouldn't want it removed from the html.

**Comment by puregraphx** [comment]
@danieliser didn't say it was a bug :) but thanks for the documentation

**Comment by danieliser** [comment]
@puregraphx no, but I can read between the lines ;)

> hope this gets fixed soon

**Comment by puregraphx** [comment]
No need to be offended. I should have phrased it as "hope this get's added soon".

**Comment by danieliser** [comment]
@puregraphx sorry, didn't mean to sound like I was offended. Was just getting point across in as few words as possible ;)

**Comment by puregraphx** [comment]
Hi @danieliser, sorry to bother you again. I have added your extra code to the functions.php but noticed that "?autoplay=1" did not work as it is appended to the existing source which already had the "?rel=0&showinfo=0". I changed it to "&autoplay=1".
I don't know if there is a way to check if "src" already contains a ? or not and thus add "?autoplay=1" or "&autoplay=1"
