### ISSUE TITLE
Add options to control z-indexs manually if needed.

### ISSUE THREAD

**Issue by danieliser** [danieliser/Popup-Maker#14]
Add options to control z-indexs manually if needed.

Original Issue: https://wordpress.org/support/topic/suggestion-z-index-options-for-cover-and-popup-box?replies=3

Temporary solution in mean time is to add something like this to your themes CSS, or using a Extra CSS plugin.

	.popmake {
	  z-index: 9999 !important;
	}
	#popmake-overlay {
	  z-index: 9998 !important;
	}

**Comment by danieliser** [comment]
1. Need to add new meta field inputs on popup display box.
2. Implement z-index values through JS retheme function.

**Comment by PennQuinn** [comment]
Cool working for me. I used...

.popmake {
  z-index: 99999!important;
}
#popmake-overlay {
  z-index: 99998!important;
}
AND tweaked the order of the admin bar
#wpadminbar {
z-index: 99997!important;
}

Thanks

**Comment by danieliser** [comment]
I may just change the defaults to something insanely high like 999999998 and 999999999, but  I bet someone then will compain that it covers their elements they want on top haha. Shameful thing is there will still be themes using the max 2147483647 or higher for some strange reason.

**Comment by danieliser** [comment]
This is added to v1.1.8
